apiVersion: apps/v1
kind: Deployment
metadata:
  name:  authservice-deployment
spec:
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - image:  registry.starboardsocial.nl/authservice:prod
          imagePullPolicy: Always
          name:  authservice
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: authservice-config
      imagePullSecrets:
        - name: starboard-registry
