name: Deploy to IRA server

on:
  workflow_call:
    
jobs:
  deploy:
    name: Deploy to IRA server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
          envkey_RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
          envkey_AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          envkey_AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
          envkey_AUTH_BASE_URL: ${{ secrets.AUTH_BASE_URL }}
          env_AUTH_ALLOWED_CALLBACK_DOMAIN_0: ${{ secrets.AUTH_ALLOWED_CALLBACK_DOMAIN_0 }}
          directory: ./
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          
      - name: Copy docker-compose.yml to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./docker-compose.yml
          remote: /home/starboard/authservice/docker-compose.yml
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
      - name: Copy .env file to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./.env
          remote: /home/starboard/authservice/.env
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
      - name: SSH to IRA and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/starboard &&
            mkdir -p authservice &&
            cd authservice &&
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ vars.REGISTRY_URL }} &&
            docker pull ${{ vars.REGISTRY_URL }}/authservice:prod &&
            docker compose up -d &&
            rm .env
